### ISSUE TITLE
Could you please provide the mentioned files from the output?

### ISSUE THREAD

**Issue by jllliang** [Shark-NLP/self-adaptive-ICL#2]
Hello! First of all, I want to express my appreciation for your work on this project. And I noticed that the following files are missing while reproducing the code: retrieve_file, retrieve_file2, pred_file. Could you please provide the mentioned files from the output?
![image](https://github.com/Shark-NLP/self-adaptive-ICL/assets/114911607/808fbf81-c430-4c27-b31e-9e3cfd48db8f)

**Comment by yxwang8775** [comment]
Thank you for reaching out and for your kind words about the project. It seems there might be a slight misunderstanding regarding the files you mentioned - retrieve_file, retrieve_file2, and pred_file. These files are actually generated as output during the retrieval and inference process and as a part of the final prediction results. Therefore, they are not required to be prepared in advance. After you run the code, these files will be automatically generated. I hope this clarifies your concern and assists you in your efforts. If you have any more questions or need further assistance, please feel free to ask.

Best regards.
