### ISSUE TITLE
what does 'index_data_path' in the 'retriever.yaml' file refer to?

### ISSUE THREAD

**Issue by fire66** [Shark-NLP/self-adaptive-ICL#3]
Initially, I filled in the path to the index file generated by the 'retriever.py' file, but the program threw an error. While examining the code, I noticed that the function for reading the 'index_data' file is
![image](https://github.com/Shark-NLP/self-adaptive-ICL/assets/92312928/236aed65-e49a-4dc0-a344-ff02d5c6f901)
![image](https://github.com/Shark-NLP/self-adaptive-ICL/assets/92312928/35a0c921-5872-4cad-8c46-876be1d5671e)

This doesn't appear to be used for reading the Faiss index file.

**Comment by yxwang8775** [comment]
Thanks for reaching out. Typically, you do not need to modify the index_data_path in the configuration file when running the code. This path is usually automatically set to the index set associated with the task you are executing, which is often the train set of the task( where you find the in-context examples). 
Best regards
